### ISSUE TITLE
DGPulldown2_python & Colorspace tagging in Sequence Display Extensions

### ISSUE THREAD

**Issue by bbgdzxng1** [jaystevens/dgpulldown#1]
Jason,

Many thanks for hosting dgpulldown in github, inadvertently [!] becoming unofficial the github maintainer of dgpulldown (Linux/MacOS) and especially your efforts in porting dgpulldown2_python, which is very cool, btw.

I came across an issue relating to `dgpulldown2_python (Version 0.5)` and `dgpulldown for Linux, Unix and macOS (Version: 1.5.1-L)` & Sequence Display Extensions/colorspace tagging.  I'm raising this ticket to log the issue for any other users, but I'm realistic in my expectations that it is unlikely to garner much attention, unless this piques your interest.

✅ Here's a working command that creates a 12 frame MPEG2video elementary stream and uses dgpulldown to insert RFF/TFF flags.

```shell
$ ffmpeg -version                                              
ffmpeg version 7.1 Copyright (c) 2000-2024 the FFmpeg developers

$ ffmpeg -hide_banner \
  -f 'lavfi' -i "testsrc2=size='ntsc':rate='ntsc-film',setdar=ratio='(4/3)',trim=end_frame=12" \
  -map '0:v:0' -codec:v 'mpeg2video' -g 12 \
  -bf:v 2 -b_strategy 0 \
  -q:v 2 -maxrate:v 8000000 -minrate:v 0 -bufsize:v 1835008 \
  -f 'mpeg2video' "./test.m2v" -y

$ grep -e '#  Version' "/opt/dgpulldown2_python/dgpulldown2.py"
#  Version 0.2 October 2, 2016
#  Version 0.5 October 7, 2016

# Now running `dgpulldown2_python` to set the RFF/TFF flags...
$ pypy3 "/opt/dgpulldown2_python/dgpulldown2.py" -i "./test.m2v" -o "./test.pulldown.m2v" -srcfps 24000/1001 -destfps 29.97

# or with python3... (dgpulldown2_python runs about three times faster in pypy3!)
$ python3 "/opt/dgpulldown2_python/dgpulldown2.py" -i "./test.m2v" -o "./test.pulldown.m2v" -srcfps 24000/1001 -destfps 29.97
```

:x: But if FFmpeg adds colorspace information to the frame, dgpulldown2_python fails.

```shell
$ ffmpeg -hide_banner \
  -colorspace:v 'smpte170m' -color_primaries:v 'smpte170m' -color_trc:v 'smpte170m' \
  -f 'lavfi' -i "testsrc2=size='ntsc':rate='ntsc-film',setdar=ratio='(4/3)',trim=end_frame=12" \
  -map '0:v:0' -codec:v 'mpeg2video' -g 12 \
  -bf:v 2 -b_strategy 0 \
  -q:v 2 -maxrate:v 8000000 -minrate:v 0 -bufsize:v 1835008 \
  -f 'mpeg2video' "./test.m2v" -y

$ pypy3 "/opt/dgpulldown2_python/dgpulldown2.py" -i "./test.m2v" -o "./test.pulldown.m2v" -srcfps 24000/1001 -destfps 29.97
```
:x: The error results in no output file being created by dgpulldown2_python.

:x: The same happens with dgpulldown for Linux, Unix and macOS Version: 1.5.1-L

```text
$ /opt/dgpulldown/dgpulldown -i "./test.m2v" -o "./test.pulldown.m2v" -srcfps 24000/1001 -destfps 29.97 
dgpulldown for Linux, Unix and macOS Version: 1.5.1-L
This version based off Version 1.0.11 by Donald A. Graft/Jetlag/timecop
Processing, please wait...
Could not open the input file!
```
This also fails if the colorspace is tagged on the output side of FFmpeg.

```shell
$ ffmpeg -hide_banner \
  -f 'lavfi' -i "testsrc2=size='ntsc':rate='ntsc-film',setdar=ratio='(4/3)',trim=end_frame=12" \
  -map '0:v:0' -codec:v 'mpeg2video' -g 12 \
  -bf:v 2 -b_strategy 0 \
  -q:v 2 -maxrate:v 8000000 -minrate:v 0 -bufsize:v 1835008 \
  -colorspace:v 'smpte170m' -color_primaries:v 'smpte170m' -color_trc:v 'smpte170m' \
  -f 'mpeg2video' "./test.m2v" -y
```

This also fails if the colorspace is tagged with an FFmpeg colorspace filter.
```shell
$ ffmpeg -hide_banner \
  -f 'lavfi' -i "testsrc2=size='ntsc':rate='ntsc-film',setdar=ratio='(4/3)',trim=end_frame=12,setparams=colorspace='smpte170m':color_primaries='smpte170m':color_trc='smpte170m'" \
  -map '0:v:0' -codec:v 'mpeg2video' -g 12 \
  -bf:v 2 -b_strategy 0 \
  -q:v 2 -maxrate:v 8000000 -minrate:v 0 -bufsize:v 1835008 \
  -f 'mpeg2video' "./test.m2v" -y
```

My hypothesis is that when FFmpeg adds colorspace information to MPEG2 frames, it adds a Sequence Display Extension which is incompatible with dgpulldown.  Sequence Display Extension can be inspected with https://media-analyzer.pro/app, which shows that when FFmpeg adds a colorspace filter, an SDE is added to the stream.

```text
MPEGVideo Sequence Display Extension #2
  start_code_prefix	00 00 01, len = 3
  start_code	181 (0xB5) <<<<<<<<<<<<<<<<<<<<<<< This seems likely to be what triggers the error.
  extension_start_code_identifier	2
  video_format	5, 'Unspecified video format'
  color_description	1
  color_primaries	6, 'SMPTE ST 170'
  transfer_characteristics	6, 'SMPTE ST 170'
  matrix_coefficients	6, 'SMPTE ST 170'
  display_horizontal_size	720 (0x2D0)
  marker_bit	1
  display_vertical_size	480 (0x1E0)
```

[This line](https://github.com/jaystevens/dgpulldown/blob/93c1ff7a9e62f5b0bf60c861e467b70f729bc0dc/dgpulldown2_python/dgpulldown2.py#L456) in the python port does include a comment indicating that SDEs may be an area of uncertainty, although the issue is not unique to your python port...

The above test case is sufficient to reproduce the error.

Workaround:
1. Hope that the input files do not include a Sequence Display Extension.
2. I did attempt to use FFmpeg's `-bsf:v filter_units='remove_types=181'` or `-bsf:v filter_units='remove_types=0x5b'` to nuke the Sequence Display Extension, but was unsuccessful.

I hope this memorization proves useful for anyone else using either dgpulldown2_python (Version 0.5) and dgpulldown for Linux, Unix and macOS (Version: 1.5.1-L).  Of course, if any python-o-phone is capable of fixing (sadly, I am not), it would be most gratefully appreciated, but my expectations are realistic and muted.

**Comment by jaystevens** [comment]
as the repo readme says this is a collection of dgpulldown forks found from the internet, it is not the place to do development on dgpulldown.

**I have no plans to update the Python version**.
The Python version was a work in progress, it was abandoned (due to performance and frustration over how Python works with Binary data).

The linux port was by "Eric @ http://renomath.org/video/linux/interlace/check.html", The linux port was a very simple port with missing features and functionality.

Final Thoughts:
Hardware DVD Players do not care / really support color space, as they could not do color space conversions.
- use the python or Eric's port and do not specify the color space during encoding.
- use a windows version that supports color space.
- fork and port the windows version to linux
- stop making DVD's, it's 2024 and NTSC on a HD/UHD TV looks terrible due to the resolution. look at authoring Bluray's with "tsmuxer"
